name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SFTP Deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          remoteDir: '.'
          localDir: '/html'
          options: 'delete'
