name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
env:
  DOCKER_IMAGE: ccharon/echoip
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1
        with:
          # username
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          local_path: './html/*'
          remote_path: '.'
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true
          delete_remote_files: false

      
