name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
        # Update the package list and install lftp

      - name: Upload files via SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -e "
          set sftp:auto-confirm yes;  # Automatically confirm any SSH host key prompts
          open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_SERVER;  # Connect to the remote server via SFTP
          mirror -R --delete ./html .;  # Upload and delete remote files not present locally
          bye  # Exit lftp
        "
