name: SFTP Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sftp-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y lftp uglifyjs uglifycss

      - name: Minify JS
        run: uglifyjs ./html/main.js -o ./html/main.js -c -m
        
      - name: Minify CSS
        run: uglifycss ./html/styles.css > ./html/styles.css.tmp && mv ./html/styles.css.tmp ./html/styles.css

      - name: Upload files via SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: lftp -u "$SFTP_USERNAME,$SFTP_PASSWORD" -p 22 sftp://$SFTP_SERVER -e 'set sftp:auto-confirm yes; set ftp:ssl-force yes; set ssl:verify-certificate yes; mirror --delete --reverse ./html . ; bye'
        
