name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sftp-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Upload files via SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: lftp -u "$SFTP_USERNAME,$SFTP_PASSWORD" -p 22 sftp://$SFTP_SERVER -e 'set sftp:auto-confirm yes; set ftp:ssl-force yes; set ssl:verify-certificate yes; mirror --delete --reverse ./html . ; bye'
        
